name: derniernoraf
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.4.0
  shared_preferences: ^2.1.1
  curved_navigation_bar: ^1.0.3
  internet_connection_checker_plus: ^1.0.1
  elegant_notification: ^1.10.0
  google_sign_in: ^6.1.4
  google_sign_in_android: ^6.1.16
  image_picker: ^0.8.7+1
  geolocator: ^9.0.2
  country_state_city_picker: ^1.2.8
  flutter_map: ^4.0.0
  google_maps_flutter: ^2.3.1
  animated_notch_bottom_bar: ^1.0.0
  cinetpay: ^1.0.7
  get: ^4.6.5
  bottom_picker: ^2.0.4
  dio: ^5.2.1+1
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.1.0
  flashtoast: ^0.0.11
  flutter_zoom_drawer: ^3.1.1
  intl_phone_field: ^3.2.0
  glass: ^1.0.1+1
  url_launcher: ^6.1.11
  http: ^0.13.6
  lottie: ^2.4.0
  cached_network_image: ^3.2.3
  read_more_text: ^0.0.5
  animated_bottom_navigation_bar: ^1.2.0
  bottom_navy_bar: ^6.0.0
  intl: ^0.18.1
  permission_handler: ^10.4.0
  date_field: ^3.0.5
  percent_indicator: ^4.2.3
  story: ^1.1.0
  story_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: lib/fonts/Oswald-Regular.ttf
    - family: Comments
      fonts:
        - asset:  lib/fonts/Oswald-Light.ttf
    - family:  Acme
      fonts:
        - asset:  lib/fonts/Acme-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
